// ============================================================
// Window film catalog from the HAMOREY retail-store price sheet.
// ============================================================

export interface WindowFilmModelSpec {
  seriesCode: string;
  seriesName: string;
  seriesPositioning: string;
  modelName: string;
  modelCode: string;
  glassPosition: 'front' | 'side';
  visibleLightTransmittance: string;
  uvRejection: string;
  solarRejection: string;
  thickness: string;
  warrantyYears: number;
  warrantyPrice: number;
  storeSuggestedPrice: number;
  retailSuggestedPrice?: number;
}

export const WINDOW_FILM_MODELS: WindowFilmModelSpec[] = [
  {
    seriesCode: 'auris',
    seriesName: '和光',
    seriesPositioning: '磁控双银系列',
    modelName: '和光70',
    modelCode: 'WF-HG70',
    glassPosition: 'front',
    visibleLightTransmittance: '70%',
    uvRejection: '99%',
    solarRejection: '58%',
    thickness: '3mil',
    warrantyYears: 10,
    warrantyPrice: 16800,
    storeSuggestedPrice: 16800,
    retailSuggestedPrice: 6880,
  },
  {
    seriesCode: 'auris',
    seriesName: '和光',
    seriesPositioning: '磁控双银系列',
    modelName: '和光25',
    modelCode: 'WF-HG25',
    glassPosition: 'side',
    visibleLightTransmittance: '25%',
    uvRejection: '99%',
    solarRejection: '58%',
    thickness: '3mil',
    warrantyYears: 10,
    warrantyPrice: 15800,
    storeSuggestedPrice: 15800,
  },
  {
    seriesCode: 'fortex',
    seriesName: '和盾',
    seriesPositioning: '安全隔热系列',
    modelName: '和盾70',
    modelCode: 'WF-HD70',
    glassPosition: 'front',
    visibleLightTransmittance: '70%',
    uvRejection: '99%',
    solarRejection: '55%',
    thickness: '4mil',
    warrantyYears: 10,
    warrantyPrice: 4980,
    storeSuggestedPrice: 4980,
    retailSuggestedPrice: 3980,
  },
  {
    seriesCode: 'fortex',
    seriesName: '和盾',
    seriesPositioning: '安全隔热系列',
    modelName: '和盾10',
    modelCode: 'WF-HD10',
    glassPosition: 'side',
    visibleLightTransmittance: '10%',
    uvRejection: '99%',
    solarRejection: '65%',
    thickness: '4mil',
    warrantyYears: 10,
    warrantyPrice: 4980,
    storeSuggestedPrice: 4980,
  },
  {
    seriesCode: 'fortex',
    seriesName: '和盾',
    seriesPositioning: '安全隔热系列',
    modelName: '和盾35',
    modelCode: 'WF-HD35',
    glassPosition: 'side',
    visibleLightTransmittance: '35%',
    uvRejection: '99%',
    solarRejection: '59%',
    thickness: '4mil',
    warrantyYears: 10,
    warrantyPrice: 4980,
    storeSuggestedPrice: 4980,
  },
  {
    seriesCode: 'lumis',
    seriesName: '和护',
    seriesPositioning: '5G护肤系列',
    modelName: '和护70',
    modelCode: 'WF-HH70',
    glassPosition: 'front',
    visibleLightTransmittance: '70%',
    uvRejection: '100%',
    solarRejection: '50%',
    thickness: '2mil',
    warrantyYears: 8,
    warrantyPrice: 3680,
    storeSuggestedPrice: 3680,
    retailSuggestedPrice: 2680,
  },
  {
    seriesCode: 'lumis',
    seriesName: '和护',
    seriesPositioning: '5G护肤系列',
    modelName: '和护15',
    modelCode: 'WF-HH15',
    glassPosition: 'side',
    visibleLightTransmittance: '15%',
    uvRejection: '100%',
    solarRejection: '58%',
    thickness: '2mil',
    warrantyYears: 8,
    warrantyPrice: 3680,
    storeSuggestedPrice: 3680,
  },
  {
    seriesCode: 'lumis',
    seriesName: '和护',
    seriesPositioning: '5G护肤系列',
    modelName: '和护25',
    modelCode: 'WF-HH25',
    glassPosition: 'side',
    visibleLightTransmittance: '25%',
    uvRejection: '100%',
    solarRejection: '56%',
    thickness: '2mil',
    warrantyYears: 8,
    warrantyPrice: 3680,
    storeSuggestedPrice: 3680,
  },
  {
    seriesCode: 'nex5',
    seriesName: '和真',
    seriesPositioning: '5G陶瓷高隔热',
    modelName: '和真75',
    modelCode: 'WF-HZ75',
    glassPosition: 'front',
    visibleLightTransmittance: '75%',
    uvRejection: '99%',
    solarRejection: '48%',
    thickness: '2mil',
    warrantyYears: 8,
    warrantyPrice: 2280,
    storeSuggestedPrice: 2280,
    retailSuggestedPrice: 1980,
  },
  {
    seriesCode: 'nex5',
    seriesName: '和真',
    seriesPositioning: '5G陶瓷高隔热',
    modelName: '和真15',
    modelCode: 'WF-HZ15',
    glassPosition: 'side',
    visibleLightTransmittance: '15%',
    uvRejection: '99%',
    solarRejection: '63%',
    thickness: '2mil',
    warrantyYears: 8,
    warrantyPrice: 2280,
    storeSuggestedPrice: 2280,
  },
  {
    seriesCode: 'nex5',
    seriesName: '和真',
    seriesPositioning: '5G陶瓷高隔热',
    modelName: '和真35',
    modelCode: 'WF-HZ35',
    glassPosition: 'side',
    visibleLightTransmittance: '35%',
    uvRejection: '99%',
    solarRejection: '56%',
    thickness: '2mil',
    warrantyYears: 8,
    warrantyPrice: 2280,
    storeSuggestedPrice: 2280,
  },
  {
    seriesCode: 'purex',
    seriesName: '和原',
    seriesPositioning: '原色膜系列',
    modelName: '和原75',
    modelCode: 'WF-HY75',
    glassPosition: 'front',
    visibleLightTransmittance: '70%',
    uvRejection: '99%',
    solarRejection: '38%',
    thickness: '1.8mil',
    warrantyYears: 5,
    warrantyPrice: 1350,
    storeSuggestedPrice: 1350,
    retailSuggestedPrice: 1280,
  },
  {
    seriesCode: 'purex',
    seriesName: '和原',
    seriesPositioning: '原色膜系列',
    modelName: '和原10',
    modelCode: 'WF-HY10',
    glassPosition: 'side',
    visibleLightTransmittance: '10%',
    uvRejection: '99%',
    solarRejection: '55%',
    thickness: '1.8mil',
    warrantyYears: 5,
    warrantyPrice: 1350,
    storeSuggestedPrice: 1350,
  },
  {
    seriesCode: 'purex',
    seriesName: '和原',
    seriesPositioning: '原色膜系列',
    modelName: '和原35',
    modelCode: 'WF-HY35',
    glassPosition: 'side',
    visibleLightTransmittance: '38%',
    uvRejection: '99%',
    solarRejection: '40%',
    thickness: '1.8mil',
    warrantyYears: 5,
    warrantyPrice: 1350,
    storeSuggestedPrice: 1350,
  },
];

export const WINDOW_FILM_POSITION_LABELS: Record<WindowFilmModelSpec['glassPosition'], string> = {
  front: '前挡',
  side: '侧挡',
};

export function formatWindowFilmPrice(value?: number): string {
  return value == null ? '-' : `¥${value.toLocaleString('zh-CN')}`;
}
